---
    - name: NCS4200 MPLS BACKBONE CREATION
      gather_facts: false
      hosts: ncs4200
      connection: network_cli
      vars_files: 
          - host_vars/interfaces.yml
          - host_vars/ospf.yml
  
      tasks:
        - name: Creating ospf.txt with respected resources
          template:
            src: ospf_protocol/ospf.j2
            dest: config_generated_from_template/ospf-{{ inventory_hostname }}.txt
  
        - name: CONFIGURE OSPF ROUTING PROTOCOL
          ios_config:
            src: templates/ospf_protocol/ospf.j2