---
    - name: NCS4200 MPLS BACKBONE CREATION
      gather_facts: false
      hosts: ncs4200
      connection: network_cli
  
      tasks:
        - name: SAVE RUNNING to STARTUP
          ios_command:
            commands:
              - wr 