---
    - name: NCS4200 MPLS BACKBONE CREATION
      gather_facts: false
      hosts: ncs4200
      connection: network_cli
      vars_files: 
          - host_vars/interfaces.yml
          - host_vars/network-clock-synce.yml
  
      tasks:
        - name: Creating network-clock-synce.txt with respected resources
          template:
            src: network_clock/network-clock-synce.j2
            dest: config_generated_from_template/network-clock-synce-{{ inventory_hostname }}.txt
      
        - name: CONFIGURE NETWORK CLOCK WITH SYNCE
          ios_config:
            src:  templates/network_clock/network-clock-synce.j2
