---
    - name: NCS4200 MPLS BACKBONE CREATION
      gather_facts: false
      hosts: ncs4200
      connection: network_cli
      vars_files: 
          - host_vars/interfaces.yml
          - host_vars/ospf.yml
  
      tasks:
        - name: Creating mpls-te.txt with respected resources
          template:
            src: mpls_te/mpls-te-ospf.j2
            dest: config_generated_from_template/mpls-te-{{ inventory_hostname }}.txt
  
        - name: CONFIGURE MPLS TE 
          ios_config:
            src:  templates/mpls_te/mpls-te-ospf.j2
