---
    - name: NCS4200 MPLS BACKBONE CREATION
      gather_facts: false
      hosts: ncs4200
      connection: network_cli
      vars_files: 
          - host_vars/interfaces.yml
  
      tasks:
        - name: Creating ip-interface.txt with respected resources
          template:
            src: interface_ip_address/ip-interface.j2
            dest: config_generated_from_template/ip-interface-{{ inventory_hostname }}.txt
  
        - name: CONFIGURE INTERFACES IPv4 ADDRESS
          ios_config:
            src: templates/interface_ip_address/ip-interface.j2