---
    - name: NCS4200 MPLS BACKBONE CREATION
      gather_facts: false
      hosts: ncs4200
      connection: network_cli
      vars_files: 
          - host_vars/interfaces.yml
          - host_vars/ospf.yml
  
      tasks:
        - name: Creating mpls-ldp.txt with respected resources
          template:
            src: mpls_ldp/mpls-ldp-ospf.j2
            dest: config_generated_from_template/mpls-ldp-{{ inventory_hostname }}.txt
  
        - name: CONFIGURE MPLS LDP 
          ios_config:
            src:  templates/mpls_ldp/mpls-ldp-ospf.j2
